// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../packages/Alea.CUDA.2.2.0.3307/lib/net40/Alea.CUDA.dll"
#r "../../packages/Alea.CUDA.IL.2.2.0.3307/lib/net40/Alea.CUDA.IL.dll"
#r "../../packages/Alea.CUDA.Unbound.2.2.0.3307/lib/net40/Alea.CUDA.Unbound.dll"
#r "../../packages/Alea.IL.2.2.0.3307/lib/net40/Alea.IL.dll"
#r "../../Graphs/DrawGraph/bin/Debug/DrawGraph.dll"
#r "../../GpuSort/bin/Debug/GpuSort.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "../../packages/FsCheck.2.5.0/lib/net45/FsCheck.dll"
#r "System.Configuration.dll"
#r "../../../../Emgu/emgucv-windesktop_x64-cuda 3.1.0.2282/bin/Emgu.CV.UI.dll"
#r "../../../../Emgu/emgucv-windesktop_x64-cuda 3.1.0.2282/bin/Emgu.CV.World.dll"
#r "../../Graphs/DirGraph/bin/Debug/DirGraph.dll"
#r "../../GpuCompact/bin/Debug/GpuCompact.dll"